### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by maticrivo** [fredsted/webhook.site#1]
is it possible to run it in a docker container? can you provide a Dockerfile?

**Comment by fredsted** [comment]
Hi! It should easily run in a container – it only requires PHP – but I don't have a Dockerfile on hand, unfortunately.

**Comment by da-n** [comment]
I had the same need so hope you don't mind that I put together a Dockerfile based on the Alpine PHP image and pushed it to Docker Hub. Feel free to use it to form basis of an official Dockerfile for your project or I am happy to maintain it separately. Either way any questions, issues or feature requests I will be able to provide. The Docker Hub repo is at https://hub.docker.com/r/dahyphenn/webhook.site/ and the Github repo is https://github.com/da-n/webhook.site.Docker and there is a full README with basic instructions.

Thanks a great application by the way.

**Comment by fredsted** [comment]
@da-n Thanks so much for this! I linked it in the readme file so far. If it would make sense to include it in this repository feel free to make a PR, otherwise I'll resolve this issue.

**Comment by maticrivo** [comment]
@da-n This is awesome! thanks so much for this!
