### ISSUE TITLE
using pusher on container

### ISSUE THREAD

**Issue by AlexandrefAraujo** [fredsted/webhook.site#10]
Hi, I'm using webhook.site container, I added my pusher credentials at .env file. When I'm receiving webhooks, the webhook page hasn't been notified, is there something to do in the pusher side?
I'm receiving webhook messages on pusher side and I need to refresh my webhook page manually to see the messages 
![image](https://user-images.githubusercontent.com/14873589/28074205-5ddec6fc-662e-11e7-91fd-3f44b635882b.png)

**Comment by fredsted** [comment]
When looking at the web inspector console, are you getting any error messages?

Is the web browser receiving any messages? I use Safari, in the web inspector, I can see a list of received messages. Are there connection_established and subscription_succeeded messages in the log? (See screenshot.)

<img width="1280" alt="screen shot 2017-07-11 at 17 36 11" src="https://user-images.githubusercontent.com/1552287/28076673-bd450062-665f-11e7-9b1c-4385a1678403.png">

**Comment by AlexandrefAraujo** [comment]
I'm receiving a code 101 but it happen just when I refresh (F5) the page.
I sent a request by postman and it wasn't shown in webhook.site, there isn't pusher notification monitoring requests.
![image](https://user-images.githubusercontent.com/14873589/28079398-a51f36ae-663e-11e7-9f38-906d87e59ac0.png)

**Comment by AlexandrefAraujo** [comment]
I'm not receiving request messages from pusher in my webhook.site

**Comment by fredsted** [comment]
Hmm, there's nothing that springs to mind. 

Since the issue is that the web browser isn't receiving the messages from Pusher, maybe it's a firewall issue – are your users behind a firewall that could limit web sockets? Did you try another browser? 

Maybe it's the credentials; on the main page the Pusher token is included like this:

```
    <script>
        var AppConfig = {
            PusherToken: "6bfb8bce49f8d53fbc4a",
        };
    </script>
```

Does it look the same on your application?

**Comment by AlexandrefAraujo** [comment]
here it is....
![image](https://user-images.githubusercontent.com/14873589/28088397-e969c550-665b-11e7-8257-81cdc6d4518e.png)

**Comment by AlexandrefAraujo** [comment]
the PusherToken should be filled with my PUSHER_APP_KEY right?

I don't know what happened.

**Comment by fredsted** [comment]
Here's how it should look in your .env file.

```
PUSHER_KEY=a7c...
PUSHER_SECRET=dc8...
PUSHER_APP_ID=269662
PUSHER_CLUSTER=eu
``

**Comment by AlexandrefAraujo** [comment]
Fixed,
I found an issue about pusher integration, it's about the pusher_cluster, I can't set up clusters not equal to **eu**
I was trying to use a project from us2 cluster and receiving this response:

> pusher.min.js:8 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance?  App key 9e27ad1bac97f8a133f8 does not exist in this cluster."}}}

so I decided to create a new project using EU cluster and it worked fine.

**Comment by fredsted** [comment]
Cool you got it working! 👍
