### ISSUE TITLE
PHP ↣ Golang

### ISSUE THREAD

**Issue by tarampampam** [fredsted/webhook.site#104]
Hi @fredsted! Thanks for your project - it's really cool!

What do you think about migrating the codebase from PHP to Golang? I have [a similar project](https://github.com/tarampampam/webhook-tester) (based on yours), but it wrote on Golang and doesn't need in socket server, Nginx, fpm, and others - all out of the box. And it works really fast!

I can help you to implement some important things. What do you think?

**Comment by fredsted** [comment]
Hi, I'm happy with PHP, and you're of course free to develop your Go version. ☺️
