### ISSUE TITLE
'Last' navigation link not working

### ISSUE THREAD

**Issue by lihop** [fredsted/webhook.site#11]
When I click the 'Last' navigation link it does not navigate to the last request, instead I get an error in the console:
```
TypeError: Cannot read property 'uuid' of undefined
```
<img width="978" alt="screen shot 2017-12-05 at 1 44 23 pm" src="https://user-images.githubusercontent.com/3696783/33593764-6d97f646-d9c3-11e7-8e5b-490d20c0a53d.png">
This error occurs even with a completely new URL that only has two requests.

**Comment by fredsted** [comment]
Should be fixed now, thanks for reporting!
