### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by renatoprogramer** [fredsted/webhook.site#12]
How about putting a form, to certra a local url and when a webhook event arrives via AJAX send to the localhost URL

**Comment by fredsted** [comment]
Hi @renatoprogramer 

Are you thinking about a way to redirect requests using AJAX? That's should be possible. How would the form look like? Which fields?

**Comment by renatoprogramer** [comment]
Then it would be a field for the user by their "IP or localhost redirection"
to and via AJAX everything that arrives it sends to the user as he wants via GET or POST.
