### ISSUE TITLE
Content-Type not being set while sending request to user

### ISSUE THREAD

**Issue by Rafal2228** [fredsted/webhook.site#16]
`redirect` method has hardcoded `Content-Type` header and doesn't take into account what user has set in settings dialog.

https://github.com/fredsted/webhook.site/blob/d2b237ce0a09c67a3c48313ce7c1937e464b7bd3/public/assets/scripts/app.js#L275

**Comment by fredsted** [comment]
@Rafal2228 Thanks for your bug report. 👍 

The fix is up now at webhook.site.
