### ISSUE TITLE
Suggestion: Reset on reaching max requests

### ISSUE THREAD

**Issue by SamAriafar** [fredsted/webhook.site#19]
Since currently system stops working on getting to the max requests limit, I'd like to suggest that you can clear oldest requests one by one while receiving new ones. Thus, the limit would remain to not let database gets too big, but system still can keep working. Besides, that would be great if we have an option to clear all stored requests at once.

**Comment by fredsted** [comment]
I've decided to close this it's now possible to use Webhook.site Premium for unlimited requests. Additionally, the open source version doesn't come with limitations.
