### ISSUE TITLE
Allow extra path

### ISSUE THREAD

**Issue by yepher** [fredsted/webhook.site#2]
Nice tool. One thing I have found useful with this sort of tool is to allow extra path after your UUID.

So instead of only allowing 
    `http://webhook.site/d5ec06c7-d2fa-4486-baef-452cb574d29e` 

also allow this URL too:
    `http://webhook.site/d5ec06c7-d2fa-4486-baef-452cb574d29e/test/123?key=value&etc=etc`
for the same monitor endpoint.

The reason is often developers provide an easy way to substitute the base URL in their app but it is harder to go and replace all the other path items. So for instance if I wanted to trace `http://example.com/v1/api/transmissions` in my app I would need to replace that with your specific URL.

I hope you find this helpful.

**Comment by fredsted** [comment]
@yepher Thanks so much for the suggestion! I've added that now and rolled it out on webhook.site.

**Comment by yepher** [comment]
I tried it out. It works well :)
