### ISSUE TITLE
Feature request: Enable CORS on URLs

### ISSUE THREAD

**Issue by suthanbala** [fredsted/webhook.site#26]
I am getting the following error from my chrome while testing it using my React App from http://localhost:8080: `Failed to load https://webhook.site/a0dc4f6a-7044-442a-89db-e14ec228da4d: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`. From my understanding, by default Chrome sends an OPTION request to the domain if it's different than current. I am suspecting, the app doesn't accept OPTIONS requests. Perhaps this package might help for Laravel: https://github.com/barryvdh/laravel-cors.

**Comment by Christilut** [comment]
CORS is simply not enabled for this server. So you can't use it in any browser that respects CORS.
You can still use it for backend applications such as Node.js because CORS is not an issue there.

For this tool to be useful for me (testing purposes), it should have a CORS origin of *

**Comment by kmcbest** [comment]
Can this feature be implemented? Like "Access-Control-Allow-Origin: *"?

**Comment by tgly307** [comment]
I hope this be implemented as soon as possible :)

**Comment by serverwentdown** [comment]
Can be done easily by configuring Nginx or any reverse proxy with the appropriate headers.

**Comment by fredsted** [comment]
It's now possible to toggle automatic CORS headers on a URL. Please let me know if you have issues with this.

**Comment by kmcbest** [comment]
@fredsted hi sir how can I get it to work? I've written [a web page](https://kmcbest.github.io/luaErrorBoard.html) to fetch webhook's url and it throws the error anyway: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://webhook.site/token/e7ffdbc3-34c9-4192-8a19-10d01a159bbd/requests?page=1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by fredsted** [comment]
@kmcbest The Webhook.site API itself isn't CORS-enabled, just the URL. You can get the correct one by clicking "Copy" in the top right corner.

**Comment by johnchaffee** [comment]
I'm trying to make a browser based ajax call to fetch the latest request and also running into the CORS issue:

```
// Request
GET https://webhook.site/token/:token_id/request/latest/raw
```

```
// Response
Access to XMLHttpRequest at 'https://webhook.site/token/:token_id/request/latest/raw' from origin 'http://localhost:1313' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Is there anything I can do on my end to solve the issue?

**Comment by fredsted** [comment]
@johnchaffee Have you checked the CORS checkbox in the user interface? 

Are you replacing the `:token_id` parameter in the URL? (If not, you'll get a 404 response which doesn't have CORS enabled)

**Comment by johnchaffee** [comment]
@fredsted Thanks for the quick reply. Yes, I'm putting my actual 36 character token in the path. I just replaced it in the examples above with `:token_id`. It results in the `No 'Access-Control-Allow-Origin' header is present on the requested resource` error. I also tried toggling the CORS Headers checkbox in the web app but it didn't seem to make any difference.

This is the ajax call I'm making in the browser that is resulting in the error:

```
    $.ajax({
      url:
      "https://webhook.site/token/MyTokenIDHere/request/latest/raw",
      method: "GET",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      data: {},
    })
```

**Comment by johnchaffee** [comment]
I disabled CORS headers in Chrome using the following command and it solved the problem. I was able to get a response from the server.

`open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir=/tmp/chrome_dev_test --disable-web-security`

However, that only works temporarily while running on my browser. So it seems the server has a CORS restriction that disallows browsers to access its resources.

**Comment by christophermalinosky** [comment]
> @johnchaffee Have you checked the CORS checkbox in the user interface?
> 
> Are you replacing the `:token_id` parameter in the URL? (If not, you'll get a 404 response which doesn't have CORS enabled)

It looks like it has just been added to the create request in the RequestController. It would be nice if they would be added across the board (all, find, and raw especially)

**Comment by dannydekr** [comment]
> 

Old message, but it seems it is still a problem. Any update om this issue?
