### ISSUE TITLE
Start a Patreon for donations

### ISSUE THREAD

**Issue by weavermedia** [fredsted/webhook.site#27]
Like [VueJS](https://www.patreon.com/evanyou/overview), [CanIUse](https://www.patreon.com/caniuse), [Vuetify](https://www.patreon.com/vuetify), [Plyr](https://www.patreon.com/plyr), [Bulma](https://www.patreon.com/jgthms), etc.

**Comment by fredsted** [comment]
Hi, thanks for the suggestion. I made a page here: https://www.patreon.com/webhooktester

Thanks for using Webhook.site!
