### ISSUE TITLE
Bookmark fails

### ISSUE THREAD

**Issue by yepher** [fredsted/webhook.site#3]
I was looking at the `webhook.site` more. I noticed it says ``. But when I try it I don't get the POSTs to that UUID.

Here is a demo of what I see:

1. Open browser (which defaults too Google.com)
2. Paste [Stored URL](http://webhook.site/#/ff0ed0ef-ed16-4223-b622-db1f415abebb) into address bar

Page does not look right and posting to the UUID does not show the requests

![failtoload](https://cloud.githubusercontent.com/assets/1359331/20397587/e285d532-acaf-11e6-8740-96b56e49e258.gif)

**Comment by fredsted** [comment]
I've had this happen sometimes, too, but it's always fixed by a reload.

It's probably the way I've coded the angular fronted. Does anyone have any ideas on how to solve this?

**Comment by fredsted** [comment]
I think I identified the issue, @yepher. It had to do with the way jQuery is loaded. I've pushed a change now, did that fix it for you?

**Comment by yepher** [comment]
Yes, it is working just fine now.
