### ISSUE TITLE
Frequent 500 errors

### ISSUE THREAD

**Issue by tflanagan** [fredsted/webhook.site#30]
I'm experiencing frequent internal server errors just trying to create a new testing url - this error changes sometimes to `curl: (52) Empty reply from server` and `curl: (35) Unknown SSL protocol error in connection to webhook.site:443`

**Comment by fredsted** [comment]
I'm taking a look now.

**Comment by tflanagan** [comment]
@fredsted thank you, no rush tho - and thanks for a wonderful service!

**Comment by fredsted** [comment]
No problem. :)

 Looks like nginx is budging under the load. Tried fiddling with some settings, and it looks like there's no errors in the log now. Please let me know if you keep experiencing issues!

**Comment by tflanagan** [comment]
Looks like it's working perfectly again.

Thanks!

**Comment by tjaskula** [comment]
I have the case since yesterday. Every request ends up as Internal Server Error 500

**Comment by fredsted** [comment]
@tjaskula Should be fixed now. Sorry about that.

**Comment by tjaskula** [comment]
It works now. Thank you @fredsted for tackling it so quickly
