### ISSUE TITLE
Add an option to view/edit the current response configuration

### ISSUE THREAD

**Issue by bmxmaki** [fredsted/webhook.site#32]
Currently the response configuration is only visible when creating a new url:
![image](https://user-images.githubusercontent.com/30684201/43076922-26a189f0-8e86-11e8-8cd4-815b661978f6.png)

**Comment by fredsted** [comment]
There's now an Edit button in the top toolbar.

**Comment by tgly307** [comment]
@fredsted Hi, is this feature added to master branch? I can't find this commit anywhere.

**Comment by fredsted** [comment]
@tgly307 I've not pushed it yet – I'll add it in the coming days

**Comment by TigerC10** [comment]
Does the response body support string substitution?  For example, if the request body comes in with a JSON payload like:
```json
{
  "data": "00000000-0000-0000-0000-000000000000"
}
```

Then the response body in form encoded could do something like:
```
data=%reqBody.data%
```
To result in:
```
data=00000000-0000-0000-0000-000000000000
```
