### ISSUE TITLE
Is there a paid instance with login? Happy to pay few bucks for this

### ISSUE THREAD

**Issue by collizo4sky** [fredsted/webhook.site#36]
Is this something you've considered?

**Comment by fredsted** [comment]
@collizo4sky Sounds like a good idea, it could definitely be done. 

How would you like auth to work? HTTP Basic auth? I guess the webhook URLs themselves shouldn't be behind a login, just the API and frontend? 

I guess I could add a new patreon plan for it. How much would you pay?

**Comment by collizo4sky** [comment]
The URL wont behind a login ofcourse. The API and frontend will similar to hookeepr.com

Perhaps $2/mo.

**Comment by fredsted** [comment]
I've added a new tier on the Patreon where this can be done.
