### ISSUE TITLE
Download webhook data

### ISSUE THREAD

**Issue by yepher** [fredsted/webhook.site#4]
## Feature Request

While working on [WebHook Viewer](http://webhook.yepher.com:3000/?hookId=626836) I found it helpful to be able to share the received webhook data with other developers. To do that I used [HAR](https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html) so it can be opened up in external tools (like Charles Proxy) to view the request/responses.

[This](https://github.com/yepher/webhook_monitor/blob/master/src/public/webhook.js#L160) is not great but is how I did it incase it can help out. It is encoded on the browser side which I think is the same way you would do it too.

**Comment by fredsted** [comment]
It's now possible to copy the contents of a URL to HAR or curl. More formats may come.
