### ISSUE TITLE
Also Forward Header to Me?

### ISSUE THREAD

**Issue by Hanwen196** [fredsted/webhook.site#40]
I was wondering that if it is possible to also forward the header to my localhost?
I found out that only body can be forwarded.

Many thanks.

![image](https://user-images.githubusercontent.com/10524800/45606819-b124ce80-ba8b-11e8-8042-767b317f71db.png)

**Comment by fredsted** [comment]
In my testing, I couldn't set some headers since XMLHTTPRequest doesn't allow setting e.g. Content-Length and Connection headers.

Would a header whitelist be OK?

**Comment by Hanwen196** [comment]
There are some security key in the header. Not so sure what you mean about header whitelist. Are you going to put the header into the body? Not so sure if this could be helpful. 

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader

I was wondering that if it is possible to have script running the browser. When the browser receive the event, it creates a new request and sends to the place I want.

Many thanks.

**Comment by fredsted** [comment]
I'm more thinking about a list of headers where you can decide specifically which headers to forward, e.g. comma-separated. 

If simply *all* headers are forwarded, I some security errors:

<img width="1277" alt="screen shot 2018-09-19 at 07 34 52" src="https://user-images.githubusercontent.com/1552287/45732878-88611e00-bbde-11e8-8e06-3c3a577afc63.png">

**Comment by micsco** [comment]
Forwarding comma-separated headers would be really good, some services are now adding things like signatures/security as a header, that needs to be forward-able.
