### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by SET001** [fredsted/webhook.site#41]
We are using wehook.site to test our webhooks but not we experiencing ESOCKETTIMEDOUT errors.

GET request to `https://webhook.site/efc65c74-ed86-4051-aac4-b13f74894a1` end's up with ESOCKETTIMEDOUT error in 80% of requests (even though we have set up 20000 seconds timeout from our side).

**Comment by fredsted** [comment]
webhook.site has been increasingly getting a lot of traffic, and since it's a free service I need donations to keep it running. Please see the main page for how to do that if you feel like it. I've upgraded the server now, hopefully it will help with the timeouts.
