### ISSUE TITLE
Create API for validating API requests

### ISSUE THREAD

**Issue by filips123** [fredsted/webhook.site#42]
Create API for validating API requests. This would be useful for testing in CI environments.

Program that is tested should do HTTP request to `https://webhook.site/some-unique-url` (the same as now).
There should be APIs to get first and last request, for example`https://webhook.site/last/some-unique-url`. This should return some JSON data of request.

There could also be API to generate new unique URL.

**Comment by fredsted** [comment]
Not sure if it's what you're looking for, but the API for webhook.site is basically public, even though I haven't documented it.

So you can do a POST to /token to generate a URL, and then GET /token/{tokenId}/requests to get all the requests in JSON. I think you should be able to accomplish what you need, although there's no API for specifically getting the first or last request.

For more, see the routes file: https://github.com/fredsted/webhook.site/blob/master/app/Http/routes.php

**Comment by filips123** [comment]
Yes, this is what I need. You should document this.
