### ISSUE TITLE
Redirect to URL [feature request]

### ISSUE THREAD

**Issue by Mattwmaster58** [fredsted/webhook.site#43]
There already exists an option to forward requests to an arbritrary address, I was wondering if we could get the functionality to redirect a request to an arbritrary URL?

**Comment by fredsted** [comment]
Hi @Mattwmaster58 Can you explain a little bit more what you're expecting? In my world, an URL and address is basically the same.

**Comment by Mattwmaster58** [comment]
I mean the same thing when I'm refer to the URL and address. 
I'm not really sure exactly how to say this. When a request is made to `https://webhook.site/#/33befb1f-e695-4368-a7db-d44bc6f27e0c`, the server would redirect to an arbritrary user-confiugrable URL. In practice in a browser this could look like the browser requesting this URL and being redirected to the user configured one.

**Comment by fredsted** [comment]
Thanks for the clarification.

The URL you linked is for the web app (the `#` in there), so you would essentially preventing a user from viewing the requests?  Could you explain the use case for this?

If you want the "actual" url to redirect, you could do something like this:

<img width="622" alt="screenshot 2018-12-04 at 07 52 00" src="https://user-images.githubusercontent.com/1552287/49423985-80565a80-f799-11e8-8618-b86d9dfd2019.png">

**Comment by Mattwmaster58** [comment]
That's the exact functionality I'm look for. Thanks for the quick reply and sorry for wasting your time!

**Comment by fredsted** [comment]
No problem, good to hear it's a solution. Closing this then :)
