### ISSUE TITLE
How to make the requests information private?

### ISSUE THREAD

**Issue by zulhfreelancer** [fredsted/webhook.site#44]
![](https://i.imgur.com/hg4s0xn.png)

Does it possible to protect all this information behind login gate?

I don't feel comfortable my requests information being public even I know it's hard for others to guess my webhook.site URL.

Thank you.

**Comment by fredsted** [comment]
Hi @zulhfreelancer, this feature is currently under development, and I hope to release it soon. :)

**Comment by zulhfreelancer** [comment]
Keep me updated. Thanks!

**Comment by fredsted** [comment]
Hi again, this was recently rolled out as a feature for Patreon supporters on Webhook.site, so closing this :)
