### ISSUE TITLE
BUG: Doesn't show JSON body

### ISSUE THREAD

**Issue by codeborn** [fredsted/webhook.site#45]
When sending this:
```curl -XPOST https://webhook.site/66725b56-75f4-487f-a781-334a63f775c3 -d '{"a json body":"that will not show"}' -H "Content-Type: application/json; charset=utf-8"```

The request shows up in the list but its JSON body is not visible. If I activate XHR forwarding (to another webhook testing site :) ) I notice that the body is actually forwarded.

However, if I omit the content-type header:
```curl -XPOST https://webhook.site/66725b56-75f4-487f-a781-334a63f775c3 -d '{"a json body":"that will not show"}'```
It shows up as ```content-type: application/x-www-form-urlencoded``` and form values contains:
```{"a_json_body":"that_will_not_show"} | (empty)```

The same happens if I set it manually (I guess cUrl did that for me...):
```curl -XPOST https://webhook.site/66725b56-75f4-487f-a781-334a63f775c3 -d '{"a json body":"that will not show"}' -H 'content-type: application/x-www-form-urlencoded'```

Expected result:
The request body is visible and displayed in its appropriate location.

Or ... am I missing something?

**Comment by codeborn** [comment]
Other than that it is a very nice webhook tester! Great work! :)

**Comment by fredsted** [comment]
Hi @codeborn, this should be fixed now. Sorry about that :)

**Comment by codeborn** [comment]
That was a wicked fast bug fix! Confirmed!
