### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by jwillmer** [fredsted/webhook.site#48]
If I try to send a request I always get:

```
{
    "success": false,
    "error": {
        "message": "Token not found",
        "id": null
    }
}
```

Is the service broken?

**Comment by fredsted** [comment]
Hi @jwillmer Try creating a new URL (blue button, top right corner).

I think there's a bug where the frontend doesn't correctly inform you when a token has expired.

**Comment by jwillmer** [comment]
Yes, that fixes the problem. Thank you!

**Comment by kashamalasha** [comment]
@fredsted Could you suggest how to check the token's expiration date?
I set the expiration in https://github.com/webhooksite/webhook.site/blob/master/config/app.php like:
```
// How many requests each URL will log before returning a 410 Gone, and the user
// will have to create a new URL.
'max_requests' => env('WEBHOOK_MAX_REQUESTS', 5000),

// Requests and tokens will expire in 14 days (default)
'expiry' => env('WEBHOOK_EXPIRY', 1209600),
```
but it looks like it doesn't effect the app after docker-compose restart.
