### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by fredsted** [fredsted/webhook.site#5]
Basic syntax highlighting for various languages:

* JSON (obviously)
* XML

Decide on which library to use:

https://highlightjs.org
http://prismjs.com

**Comment by yepher** [comment]
[Ace](https://ace.c9.io/#nav=about) is a good and easy way to do it. Also make it easy to collapse and expand sections. [Here](https://github.com/yepher/webhook_monitor/blob/master/src/public/index.html#L55) is an example of it.

**Comment by micsco** [comment]
@fredsted have you thought about how you'd like this to be implemented? This is something I might have a go at this weekend.

**Comment by fredsted** [comment]
@micsco I've been thing of using an editor component like Ace as was suggested, as a bonus I think it also supports other formats like XML which would be really handy. Not sure how well it fits with the existing Angular app, it's not very well written right now so might have to move some things around for something like Ace to fit in.

**Comment by micsco** [comment]
What about something like [PrismJS](https://prismjs.com/)? 

It's not an editor, but I'm not sure there are editing needs for webhooks?

**Comment by micsco** [comment]
Another option is [HighlightJS](https://highlightjs.org/).

**Comment by fredsted** [comment]
I wonder if  there's any package that can do formatting as well? Couldn't find anything about it on the PrismJS or HighlightJS website. Right now there's only JSON formatting, but lots of users also post XML to Webhook.site. Something that could auto-pretty print various formats would be neat.

**Comment by micsco** [comment]
Looks like we may have to add formatting for XML separately. I'll create a ticket to track it.

**Comment by micsco** [comment]
I've created #60 to track XML formatting/pretty printing.
