### ISSUE TITLE
Feature Request: Private site using G-Suite authentication

### ISSUE THREAD

**Issue by micsco** [fredsted/webhook.site#59]
The ability to secure webhook data is important.

When I've been developing against webhooks, sometimes it's hard to get dummy or fake data, instead, the webhook is sent with real/client/private information. The ability to secure either the entire webhook site or a single token behind a login such as G-Suite login would be ideal.

I can see you have a paid patreon feature "Password Protection". 

Ideally, I'd like to self-host this, securing by requiring G-Suite login to view any webhooks received.

**Comment by maxnucci** [comment]
+1

**Comment by mmihalev** [comment]
+1

**Comment by fredsted** [comment]
I'd recommend using something like [oauth2_proxy](https://github.com/pusher/oauth2_proxy), it's out of scope for this project.
