### ISSUE TITLE
On-premise docker deployment failed

### ISSUE THREAD

**Issue by Code2Life** [fredsted/webhook.site#62]
Hi, I wanna deploy one in local test environment. but got errors when "npm install", node-saas lib couldn't be compiled correctly, and same errors got from "docker-compose up". 

make: Entering directory '/app/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/root/.node-gyp/8.16.0/include/node -I/root/.node-gyp/8.16.0/src -I/root/.node-gyp/8.16.0/deps/openssl/config -I/root/.node-gyp/8.16.0/deps/openssl/openssl/include -I/root/.node-gyp/8.16.0/deps/uv/include -I/root/.node-gyp/8.16.0/deps/zlib -I/root/.node-gyp/8.16.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
Killed
ERROR: Service 'webhook' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 137

**Comment by fredsted** [comment]
Looks like an OOM error or something. Hard to say when it just says `Killed`.

You can use the prebuilt images by reverting this change: https://github.com/fredsted/webhook.site/commit/e9fc6f16877952491a092dfd2582d2d1211fdd77
