### ISSUE TITLE
Question: timestamps

### ISSUE THREAD

**Issue by abrahamhuie** [fredsted/webhook.site#66]
Are they in UTC? What convention do you use?

**Comment by fredsted** [comment]
Yep, it's UTC. I've thought about displaying timestamps with the users' browser time zone, never got that far.

**Comment by abrahamhuie** [comment]
Seems like that would be a cool solution. I can muster with UTC for now, though. Just wanted to confirm with you!

**Comment by RvdHNL** [comment]
Also would like user timezone.

**Comment by fredsted** [comment]
Timestamps are now displayed in the browser timezone and locale format as well as in a relative format. 

It's still possible to view the UTC time by hovering over the date in the details table, upon which the UTC time is displayed in the title tag.
