### ISSUE TITLE
BUG report: Cannot delete single requests

### ISSUE THREAD

**Issue by guibranco** [fredsted/webhook.site#72]
**Error:** When you want to delete a single request, clicking in the red-X icon right-side of the request id, nothing happens. In the Developer Tools of the browser, appears a script error.

![error-webhook-site](https://user-images.githubusercontent.com/3362854/61324058-e43d0900-a7e7-11e9-813a-dd2385ff49a0.gif)

**Comment by fredsted** [comment]
Fixed now! Sorry, didn't see this earlier.
