### ISSUE TITLE
Feature request: get a list of all requests raw link

### ISSUE THREAD

**Issue by kmcbest** [fredsted/webhook.site#74]
I'd like to have a list of all requests to my unique URL returned, so that I can parse them. How can I do it?

**Comment by fredsted** [comment]
You can use this call:

`GET https://webhook.site/token/<UUID>/requests?page=1`

With that you can loop through all requests sent to a URL.

**Comment by kmcbest** [comment]
Cool. Exactly what I need, even in JSON!
