### ISSUE TITLE
Not able to enable XHR Redirect for web hooks

### ISSUE THREAD

**Issue by nayanap-qualtrics** [fredsted/webhook.site#77]
I am able to add settings for XHR redirect but the UI radio button to enable XHR redirect is not clickable anymore hence my requests are not getting redirected. Also changes to settings are not getting saved properly.

**Comment by fredsted** [comment]
Thanks for reporting this. Please try again, it should be fixed now!

**Comment by nayanap-qualtrics** [comment]
Thank you so much for a quick resolution. Appreciate that !
