### ISSUE TITLE
Making filesystem configurable via environment variables

### ISSUE THREAD

**Issue by ryanhelms** [fredsted/webhook.site#79]
Hey Fred,

Great work on this product. We use this in conjunction with portainer to quickly deploy it as a stack. We don't do any PHP internally, so forking, setting up builds and such to get this functionality seems like overkill before asking first. 

Do you think you could setup the config/filesystem.php file to be configurable via environment variables like some of the others. I'd really like to be able to set the filesystem as s3 to persist our tokens through container / stack restarts.

Any help would be appreciated and thanks!

**Comment by fredsted** [comment]
Hi ryan, the filesystem isn't used—all the data is stored in Redis.
