### ISSUE TITLE
Implement Pusher alternative

### ISSUE THREAD

**Issue by maticrivo** [fredsted/webhook.site#8]
Hey, have you considered using websocket instead of pusher? to minimize dependencies on external providers..

I'm willing to create a PR if you're interested in this solution

**Comment by fredsted** [comment]
Making Webhook Tester free of external deps would indeed be nice, feel free to create a PR!

**Comment by fredsted** [comment]
Now webhook.site has also reached our sponsored plan's connection limit from Pusher.com, so I'll be looking at implementing an alternative.
