### ISSUE TITLE
Make URL parsing less strict

### ISSUE THREAD

**Issue by Nowaker** [fredsted/webhook.site#81]
Before Thanksgiving I bought a Premium version, created a new webhook site starting with `f4401c90`, enabled password protection on it, and tested it actually worked - both webhook at `https://webhook.site/f4401c90-snipped`, as well as the UI at https://webhook.site/#!/f4401c90-snipped.

My intent was to leave this running for the weekend, and see all the requests today. I checked today and it no longer works. https://webhook.site/#!/f4401c90-4940-snipped no longer prompts for password. And the page seems borked when I visit it (the unique URL is incorrect).

![image](https://user-images.githubusercontent.com/611746/70090164-3f2c9c80-15df-11ea-9c63-f9d2f02c54d5.png)

However, the webhook itself at `https://webhook.site/f4401c90-snipped` does function, as it returns the JSON content I configured it to return:

```
{
  "autoConfirm": false,
  "attributes": {
    "nowakertest": "test"
  }
}
```

Can you please look into the problem and fix it so that I can access my webhook request history at https://webhook.site/#!/f4401c90-snipped? Thanks!

**Comment by fredsted** [comment]
Hi @Nowaker, the token is still there – the password is still present, and there's about 426 requests.

Please send me a mail at support@webhook.site and I'll send you the correct URL.

**Comment by Nowaker** [comment]
@fredsted The issue was I saved my webhook link with `/` at the end - for whatever reason. I think the reason might be the link looks like `https://webhook.site/#!/WEBHOOK_ID/EVENT_ID/1`, so I set aside `https://webhook.site/#!/WEBHOOK_ID/` for later. So no help needed at this point. Sorry for bothering. :)

At this point, the only thing I'd suggest looking at is:

- [ ] Show a friendly error message if an incorrect webhook ID is passed. (As you can see on the screenshot, the site is in an incorrect state.)
- [ ] Ignore a trailing`/` in links so `https://webhook.site/#!/WEBHOOK_ID/` works just like `https://webhook.site/#!/WEBHOOK_ID`

Thanks!

**Comment by fredsted** [comment]
Hi, thanks for the feedback. I agree with both suggestions!

**Comment by fredsted** [comment]
This has now also been solved.
