### ISSUE TITLE
Redirects not happening automatically 

### ISSUE THREAD

**Issue by nayanap-qualtrics** [fredsted/webhook.site#82]
I have a webhook set up to redirect to my local machine. When I am making POST requests to the webhook, the requests are not getting redirected to my localhost automatically. If I click on the request and click redirect now then I am receiving requests. Also I am not seeing the incoming requests in the UI until I refresh it.

**Comment by fredsted** [comment]
Hi @nayanap-qualtrics , there's been some issues with the queue crashing overnight, but it's restored now and sending the full backlog. Try again an hour or two after this message and it should work.

**Comment by nayanap-qualtrics** [comment]
Yes. The issue seems to be resolved. Thank you !!
