### ISSUE TITLE
Bug: "Next page" results in 401 Unauthorized

### ISSUE THREAD

**Issue by Nowaker** [fredsted/webhook.site#83]
Happens on https://webhook.site/#!/f4401c90-snipped.

1. [ ] Click "Next page" - get 401 Unauthorized in the console.
2. [ ] Click "Next page" - nothing happens, no user feedback - UI error handling problem.

Regarding the latter, this happens very often in single page applications. It's easy to forget to handle an error. There's a need for global error handler that will display an error if any request fails. Below is how it got done at my company.

![image](https://user-images.githubusercontent.com/611746/70190780-8472cc00-16bc-11ea-93fe-2d2c20300147.png)

And the implemented design: 
![image](https://user-images.githubusercontent.com/611746/70190626-01517600-16bc-11ea-9309-b6e7c07193b9.png)

Here's something for JQuery: https://stackoverflow.com/questions/17989961/jquery-catch-any-ajax-error. I'm sure an equivalent mechanism exists for whatever webhook.site uses.

**Comment by fredsted** [comment]
Thanks for the feedback @Nowaker , I'll take a look as soon as possible.

**Comment by Nowaker** [comment]
@fredsted Any news on that? I still can't access these reports because of 401.

**Comment by fredsted** [comment]
@Nowaker Sorry about the delay. It's fixed now.

**Comment by Nowaker** [comment]
Thanks! It works now.
