### ISSUE TITLE
Misconfigured IPv6 address starting December 18 14:45 ET?

### ISSUE THREAD

**Issue by DWvanGeest** [fredsted/webhook.site#84]
Hello,

Thanks for this very useful tool! We use it a lot at pagerduty.com and so do our customers :-).

We noted yesterday that webhooks from PagerDuty to `webhook.site` began failing yesterday at about 14:45 ET. After some investigation, it [appears](https://mxtoolbox.com/SuperTool.aspx?action=aaaa%3awebhook.site&run=toolpage#) that the `AAAA` record for webhook.site is set to `fe80::2d8:61ff:fea8:bb96`, which is [reserved as a link-local address](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6).

Trouble is, a Squid proxy with default configuration will recognize this as a local address and deny access to `webhook.site`. I'm currently investigating how to work around this in Squid, but thought you might like to know for the sake of other users.

I'm by no means an IPv6 expert, so let me know if I'm missing something in this analysis. Thanks!

**Comment by fredsted** [comment]
Hi David, sorry about that. The AAAA records should point to a valid IPv6 address now (2a01:4f8:141:1d3::2). I'm not able to test that it works though, my ISP doesn't have IPv6 support.

**Comment by DWvanGeest** [comment]
No worries! I can confirm that our webhooks are succeeding again. Thanks for the quick fix.
