### ISSUE TITLE
New line chars are stripped (not shown) from request body

### ISSUE THREAD

**Issue by modax** [fredsted/webhook.site#85]
Hello,

It seems that new line characters are stripped away during request body processing. E.g.:

```
printf "%s\n%s\n%s\n%s\n" a b c d | curl -H 'Content-Type: text/plain' -v -d@- https://webhook.site/38e09213-6ad6-42b0-8cb5-890939757c31
```

results into both ["raw content" page](https://webhook.site/token/38e09213-6ad6-42b0-8cb5-890939757c31/request/0a1b9023-a679-4c0d-aa35-e487a0090afa/raw) and [html preview at permalink](https://webhook.site/#!/38e09213-6ad6-42b0-8cb5-890939757c31/0a1b9023-a679-4c0d-aa35-e487a0090afa/1) not showing any new lines. Adding "\r" to the mix does not seem to help the case.

Thanks!

**Comment by fredsted** [comment]
Hi @modax, apparently with curl you have to use the `--data-binary` flag for curl to preserve newlines in the request body.

This worked for me: 

`printf "%s\n%s\n%s\n%s\n" a b c d | curl -H 'Content-Type: text/plain' -v --data-binary @- https://webhook.site/xxxxx`

**Comment by modax** [comment]
@fredsted: Thanks a lot for the prompt response! Oh my bad, you are right! Why would curl do that by default is beyond me, very unintuitive! Thanks again!

**Comment by fredsted** [comment]
Yeah, it's kind of weird :)
