### ISSUE TITLE
"Last" jumps to last loaded item, not to the last page

### ISSUE THREAD

**Issue by Nowaker** [fredsted/webhook.site#86]
![image](https://user-images.githubusercontent.com/611746/72484375-a4bc9d00-37c9-11ea-9db5-3d37574508b6.png)

This is pagination control. First and last must jump to first and last page, respectively. At this moment, "Last" button is pretty useless. Plus, without a way to jump to last page, I must click a hundred times or so before I'm able to reach the last page.

**Comment by fredsted** [comment]
This should now be fixed.

**Comment by Nowaker** [comment]
Thanks!
