### ISSUE TITLE
Not working in android app always showing"internal server error 500"

### ISSUE THREAD

**Issue by kulvinder18may** [fredsted/webhook.site#9]
I'm just trying to post data from android app to webhook.site url , but it always failed with 500 error, can you please help

**Comment by fredsted** [comment]
@kulvinder18may  

2 questions:

1. Can you reproduce it using `curl`?
2. Could you post the URL you're using? Something like http://webhook.site/372a3591-e0ca-4e08-b4c2-2dfdab8a66ef

**Comment by kulvinder18may** [comment]
http://webhook.site/4440279d-3bbb-4540-a481-5778dd864faf?api-key=234234123&number={phone_number}&name={caller_name}&line={line}&se=start
I don't know curl., this is the url i'm using .
if i'm trying to hit "http://webhook.site" then getting success 200, but after adding key and params it returns 500

**Comment by fredsted** [comment]
@kulvinder18may 

Looks it it returns 500 if there's no User-Agent header on the http request.

I'll submit a PR when i have time, probably in a couple days. Try adding the header, then it should work.

**Comment by kulvinder18may** [comment]
Yessss...now working perfect...Thank you so much

**Comment by fredsted** [comment]
Fixed in `c9fc829`.
