### ISSUE TITLE
site broken due to javascript error

### ISSUE THREAD

**Issue by da-vaibhav** [fredsted/webhook.site#93]
docs site https://docs.webhook.site/ is broken
error screenshot 
<img width="1292" alt="Screenshot 2020-06-30 at 12 08 07 AM" src="https://user-images.githubusercontent.com/1468518/86043203-f69a6c00-ba65-11ea-8208-e0ba94a28e8d.png">

**Comment by fredsted** [comment]
Fixed. Moved to new docs system
