### ISSUE TITLE
Rate Limiting on Webhook

### ISSUE THREAD

**Issue by clay584** [fredsted/webhook.site#96]
I am running a local instance of webhook site and I am getting 429 Too Many Requests and getting rate limited. I have it behind an NGINX proxy just using proxy_pass and SSL. I cannot find anything that would suggest that NGINX does rate-limiting without explicitly configuring it, so I am thinking that perhaps the webhook code is rate-limiting in some way. I have looked through your codebase and didn't see anything that stands out. Do you know if there is built-in rate-limiting, and if so, is there a way to disable that or adjust the limits?

**Comment by fredsted** [comment]
Hi, you can remove the rate limiting by uncommenting the following line: https://github.com/fredsted/webhook.site/blob/master/app/Http/Kernel.php#L42

**Comment by juanjoDiaz** [comment]
Hi @fredsted ,

Would it be possible to configure throttling via environment variables or some other configuration mechanism that doesn't require changing the actual code?

**Comment by fredsted** [comment]
@juanjoDiaz I wouldn't be against a PR removing it.

**Comment by juanjoDiaz** [comment]
Do yo mean removing it completely instead instead of making it configurable?

**Comment by fredsted** [comment]
I would be happy with both

**Comment by Nikakto** [comment]
@fredsted really? Still is not configurable?

**Comment by fredsted** [comment]
@Nikakto really? Still is no PR?

**Comment by juanjoDiaz** [comment]
I moved to use another solution.

**Comment by fredsted** [comment]
I'm not 100% sure why no-one seem to have the wherewithal to submit a PR to remove it, but there you go.
