### ISSUE TITLE
Does not work with multipart/form-data

### ISSUE THREAD

**Issue by m42e** [fredsted/webhook.site#99]
If some files are transmitted using mulipart/form-data method they are not recognized.

With curl it works, but using requests it does not.

```
import requests
requests.request('post', 
'https://webhook.site/a3c6f668-4154-4c71-a6a0-b219ee296eee', 
files={'file':open('id.txt')})
```

No file will be shown.

**Comment by fredsted** [comment]
Hi @m42e, the issue should be fixed now on Webhook.site. Thank you for reporting it.

**Comment by hirenshah** [comment]
Is this supposed to be fixed in the open source / Docker version?
